version: "3.9"
services:
  bot:
    build: .
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
    volumes:
      - ./:/app
    command: python -m src.main
  ui:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - ./:/app
    command: streamlit run ui/dashboard.py --server.port=8501 --server.address=0.0.0.0
